# Generated by Django 4.0.6 on 2022-08-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_album_user_id_photo_user_id_alter_album_album_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_image',
            new_name='cover_image',
        ),
    ]
