# Generated by Django 4.0.6 on 2022-07-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='cover_image',
            new_name='album_image',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_image',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
