# Generated by Django 4.0.6 on 2022-08-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(default='', max_length=30, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='family/')),
            ],
        ),
    ]
