# Generated by Django 4.0.6 on 2022-07-27 20:17


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),

                ('family_name', models.CharField(default='', max_length=31, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='family/')),
                ('bio', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('password', models.CharField(default='', max_length=31, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),

            ],
        ),
    ]
